<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Title>Dotmim.Sync.PostgreSql</Title>
		<Summary>PostgreSQL sync provider for client and server roles.</Summary>
		<Description>PostgreSQL sync provider to manage synchronization between relational databases.</Description>

	</PropertyGroup>
	<PropertyGroup>
		<NoWarn>$(NoWarn)SA0001;SA1202;CA1308;CA1305;CA1822;CA1834;SA1600;IDE0017;CA2249;CA1866;CA2100;CA1307;CA1310;</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\docs\assets\packageIcon.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Dotmim.Sync.Core\Dotmim.Sync.Core.csproj" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
		<PackageReference Include="Npgsql" Version="8.0.3" />
	</ItemGroup>

</Project>
