<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>

		<Authors>Sébastien Pertus</Authors>
		<Company>Microsoft</Company>
		<Title>Dotmim.Sync.SqlServer</Title>
		<Summary>SQL Server sync provider for client and server roles.</Summary>
		<Description>SQL Server sync provider to manage synchronization between relational databases.</Description>
		<RepositoryType>git</RepositoryType>
		<ApplicationIcon>favicon.ico</ApplicationIcon>
		<PackageIcon>packageIcon.png</PackageIcon>
	</PropertyGroup>
	<PropertyGroup>
		<NoWarn>$(NoWarn)SA0001;SA1202;CA1308;CA1305;CA1822;CA1834;SA1600;IDE0017;CA2249;CA1866;CA2100;CA1307;CA1310;</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\..\docs\assets\packageIcon.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
		<ProjectReference Include="..\Dotmim.Sync.Core\Dotmim.Sync.Core.csproj" />
	</ItemGroup>

</Project>