<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>

		<Authors>Sébastien Pertus</Authors>
		<Company>Microsoft</Company>
		<Title>Dotmim.Sync.MySql</Title>
		<Summary>MySQL sync provider for client and server roles.</Summary>
		<Description>MySQL sync provider to manage synchronization between relational databases.</Description>
		<RepositoryType>git</RepositoryType>
		<ApplicationIcon>favicon.ico</ApplicationIcon>
		<PackageIcon>packageIcon.png</PackageIcon>

	</PropertyGroup>
	<PropertyGroup>
		<NoWarn>$(NoWarn)SA0001;SA1202;CA1308;CA1305;CA1822;CA1834;SA1600;IDE0017;CA2249;CA1866;CA2100;CA1307;CA1310;</NoWarn>
	</PropertyGroup>
	<!--generate NUGET package including symbols ans source on each release build -->
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DefineConstants>MYSQL</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DefineConstants>TRACE;MYSQL</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\docs\assets\packageIcon.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\Dotmim.Sync.Core\Dotmim.Sync.Core.csproj" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MySqlConnector" Version="2.3.7" />
	</ItemGroup>


</Project>
